name = "porter_stemmer"
version = "1.0.0"
description = "Porter word stemming in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "porter_stemmer" }
links = [
  { title = "Website", href = "https://tartarus.org/martin/PorterStemmer/" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
porter_stemming = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
